nohup: ignoring input
/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/backbones/__init__.py", line 6, in <module>
    from .fast_scnn import FastSCNN
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/backbones/__init__.py", line 6, in <module>
    from .fast_scnn import FastSCNN
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/backbones/__init__.py", line 6, in <module>
    from .fast_scnn import FastSCNN
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/backbones/__init__.py", line 6, in <module>
    from .fast_scnn import FastSCNN
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/decode_heads/decode_head.py", line 11, in <module>
    from ..losses import accuracy
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/home/haeun1107/decs_jupyter_lab/MaskCLIP/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6520) of binary: /home/haeun1107/.conda/envs/torch191/bin/python
Traceback (most recent call last):
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/haeun1107/.conda/envs/torch191/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
         tools/train.py FAILED         
=======================================
Root Cause:
[0]:
  time: 2025-07-19_17:43:17
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 6520)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2025-07-19_17:43:17
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 6521)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2025-07-19_17:43:17
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 6522)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[3]:
  time: 2025-07-19_17:43:17
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 6523)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

